name: clang-format-check

on:
  pull_request:
    branches:
    - intel

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get clang-format first
      run: sudo apt-get install -yqq clang-format-9

    - uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Get clang-format-diff.py tool
      run: |
        wget https://raw.githubusercontent.com/intel/llvm/sycl/clang/tools/clang-format/clang-format-diff.py
        chmod u+x clang-format-diff.py
      
    - name: Run clang-format for the patch
      shell: bash {0}
      run: |
        git clang-format ${GITHUB_SHA}^1
        git diff > ./clang-format.patch
    # Add patch with formatting fixes to CI job artifacts
    - uses: actions/upload-artifact@v1
      with:
        name: clang-format-patch
        path: ./clang-format.patch

    - name: Check if clang-format patch is empty
      run: bash -c "if [ -s ./clang-format.patch ]; then cat ./clang-format.patch; exit 1; fi"
